model:
    arch: unet
    input_nc: 4
    output_nc: 6
    num_downs: 7
    ngf: 64
    norm_layer: 'batch' # or 'instance'
    use_dropout: True
data:
    name: 'isprs'
    dataset: threeCity
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 512
    n_classes: 6
    channels: 4
    path: /home/robotics/ma_thesis_data/isprs/dataset512/Potsdam8cm
    suffix: '.png'
training:
    epochs: 1000
    batch_size: 2
    val_interval: 200
    n_workers: 1
    print_interval: 10
    optimizer:
        name: 'adam'
        lr: 1.0e-3
        weight_decay: 0.0001
        #momentum: 0.9
        betas: [0.95, 0.999]
    loss:
        name: 'cross_entropy'
    lr_schedule:
        name: 'plateau'
        mode: 'min'
        factor: 0.2
        threshold: 0.001
        patience: 5
    resume:
    checkpoint: /home/robotics/SemsegDA/checkpoints/unet_isprs/unet_isprs_best_model.pkl
