model:
    arch: fcn
data:
    dataset: dsm
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 512
    n_classes: 2
    channels: 1
    path: /home/robotics/ma_thesis_data/isprs/dataset512_dsm/Potsdam8cm
    suffix: '.png'
training:
    augmentations:
        hflip: 0.5
        vflip: 0.5
        rotate:
            max_degree: 360
            split: 4
    train_iters: 300000
    batch_size: 2
    val_interval: 100
    n_workers: 1
    print_interval: 10
    optimizer:
        name: 'adam'
        lr: 1.0e-4
        weight_decay: 0.0001
        #momentum: 0.9
        betas: [0.95, 0.999]
    loss:
        name: 'cross_entropy'
    lr_schedule:
    resume: # /home/robotics/pytorch-semseg/runs/fcn_v1_3city/14_42_43_081819_focal_loss/fcnV1_threeCity_best_model.pkl
